services:
  postgres:
    image: postgres:18-bookworm
    restart: unless-stopped
    container_name: mol-postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=development-database-password
      - POSTGRES_DB=mol
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
    external: true
    name: 0732ae530ab79dcd2ede8d4a749ac6361cf215f2c4bd3e13d7bd965480c394f5
